apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-arcadia
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/arunhotra/argocd-app-config.git
    targetRevision: HEAD
    path: prod-arcadia
  destination: 
    server: https://kubernetes.default.svc
    namespace: prod-arcadia

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true